### ISSUE TITLE
Init fails with error "getTargetTexture4 is not a function"

### ISSUE THREAD

**Issue by vorg** [pissang/claygl-advanced-renderer#1]
I'm trying to run example code  from README and I get

`TypeError: this._gBufferPass.getTargetTexture4 is not a function. (In 'this._gBufferPass.getTargetTexture4()', 'this._gBufferPass.getTargetTexture4' is undefined)`

![screen shot 2018-03-26 at 09 53 46](https://user-images.githubusercontent.com/171001/37896420-a43c29d2-30db-11e8-9221-0ebb2e89bc00.png)

**Comment by pissang** [comment]
Hi @vorg . It's because this project needs the latest code of ClayGL to support velocity buffer.  I just released [ClayGL 1.1.2](https://github.com/pissang/claygl/releases/tag/1.1.2) and it should be fixed now.

**Comment by vorg** [comment]
Updating to ClayGL 1.1.2 helped
